[features]
seeds = false
skip-lint = false
[programs.devnet]
sol_social = "7CuooyeTewXB5v3V22gmkoZFKDBdFmkb68mhozGghcxt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/threedevx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
