[features]
seeds = true
skip-lint = false
[programs.localnet]
sol_social = "7CuooyeTewXB5v3V22gmkoZFKDBdFmkb68mhozGghcxt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/threedevx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
